name: 🐳 Build & Run Docker

# Trigger: setiap push ke cabang mana saja dan pull request
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Docker Buildx (untuk build multi-platform jika perlu)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Set up Docker Compose
      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      # 4. Build dan jalankan container via docker-compose
      - name: Build & run with docker-compose
        run: |
          docker-compose up --build --abort-on-container-exit
          
      # 5. (Opsional) Jika ada error, tampilkan log container
      - name: Show container logs on failure
        if: failure()
        run: |
          # nama container sesuai dengan docker-compose.yml kamu
          docker logs general-fuzzy-logic || true